version: "3.7"

services:
  fastapi:
    image: fastapi:1.0
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - 8080:8080
    volumes:
      - ./app:/code/app
    depends_on:
      - ganache

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545
    volumes:
      - ./ganache_data:/ganache_data
    entrypoint: 
      - node
      - /app/ganache-core.docker.cli.js
      - --deterministic
      - --db=/ganache_data
      - --mnemonic
      - 'minimum symptom minute gloom tragic situate silver mechanic salad amused elite beef'
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --debug