FROM python:3.10

WORKDIR /code
COPY ./requirements.txt /code/requirements.txt

RUN pip install --trusted-host pypi.python.org --trusted-host files.pythonhosted.org --trusted-host pypi.org --no-cache-dir --upgrade -r /code/requirements.txt